{{- range $fullName, $svc := .Values.services }}
{{- $svc := mergeOverwrite (deepCopy $.Values.default) (deepCopy $svc) }}
{{- if $svc.enabled }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
spec:
  rules:
  {{- if $svc.ingress.hosts }}
  {{- range $host := $svc.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
        {{- range $path := $svc.ingress.paths }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ (index $svc.service 0).port }}
        {{- end -}}
  {{- end -}}
  {{- end -}}
{{- end -}}
{{- end -}}